-- V1__Create_basic_enums.sql
-- Create enum types for critical/fixed data

CREATE TYPE ROLE_ENUM AS ENUM ('USER', 'ADMIN');
CREATE TYPE ACCOUNT_STATUS_ENUM AS ENUM ('ACTIVE', 'CLOSED', 'SUSPENDED');
CREATE TYPE TRANSACTION_TYPE_ENUM AS ENUM (
    'DEPOSIT',
    'WITHDRAWAL',
    'TRANSFER_INTERNAL',
    'TRANSFER_EXTERNAL'
);
CREATE TYPE TRANSACTION_CATEGORY_ENUM AS ENUM (
    'FOOD',
    'GROCERIES',
    'TRANSPORT',
    'SHOPPING',
    'ENTERTAINMENT',
    'HEALTH',
    'TRAVEL',
    'SUBSCRIPTIONS',
    'INCOME',
    'OTHERS'
);
CREATE TYPE CLIENT_TYPE_ENUM AS ENUM ('PF', 'PJ');
CREATE TYPE SEX_TYPE_ENUM AS ENUM ('M', 'F', 'O');
CREATE TYPE CURRENCY_ENUM AS ENUM ('EUR', 'USD', 'RON', 'GBP');
